// <auto-generated />
namespace Alkobazar.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4));
        
        string IMigrationMetadata.Id
        {
            get { return "201804221544498_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
